// Small curated starter list, not a comprehensive blocklist. Domains are
// matched by suffix (see classify.js), so listing "doubleclick.net" also
// matches "ads.doubleclick.net" etc.
export const TRACKER_DOMAINS = [
  // Ad networks / exchanges
  { domain: "doubleclick.net", category: "ad_tracker" },
  { domain: "googlesyndication.com", category: "ad_tracker" },
  { domain: "googleadservices.com", category: "ad_tracker" },
  { domain: "adnxs.com", category: "ad_tracker" },
  { domain: "adsrvr.org", category: "ad_tracker" },
  { domain: "criteo.com", category: "ad_tracker" },
  { domain: "criteo.net", category: "ad_tracker" },
  { domain: "taboola.com", category: "ad_tracker" },
  { domain: "outbrain.com", category: "ad_tracker" },
  { domain: "pubmatic.com", category: "ad_tracker" },
  { domain: "rubiconproject.com", category: "ad_tracker" },
  { domain: "casalemedia.com", category: "ad_tracker" },
  { domain: "openx.net", category: "ad_tracker" },
  { domain: "bidswitch.net", category: "ad_tracker" },
  { domain: "mopub.com", category: "ad_tracker" },
  { domain: "unity3d.com", category: "ad_tracker" },
  { domain: "applovin.com", category: "ad_tracker" },
  { domain: "adjust.com", category: "ad_tracker" },
  { domain: "kochava.com", category: "ad_tracker" },
  { domain: "chartboost.com", category: "ad_tracker" },
  { domain: "vungle.com", category: "ad_tracker" },
  { domain: "ironsrc.com", category: "ad_tracker" },
  { domain: "tapjoy.com", category: "ad_tracker" },
  { domain: "advertising.com", category: "ad_tracker" },
  { domain: "amazon-adsystem.com", category: "ad_tracker" },
  { domain: "media.net", category: "ad_tracker" },
  { domain: "sharethrough.com", category: "ad_tracker" },
  { domain: "spotxchange.com", category: "ad_tracker" },
  { domain: "smartadserver.com", category: "ad_tracker" },
  { domain: "adroll.com", category: "ad_tracker" },
  { domain: "bluekai.com", category: "ad_tracker" },
  { domain: "demdex.net", category: "ad_tracker" },
  { domain: "everesttech.net", category: "ad_tracker" },
  { domain: "adform.net", category: "ad_tracker" },
  { domain: "moatads.com", category: "ad_tracker" },
  { domain: "graph.facebook.com", category: "ad_tracker" },
  { domain: "connect.facebook.net", category: "ad_tracker" },
  { domain: "an.facebook.com", category: "ad_tracker" },
  { domain: "bat.bing.com", category: "ad_tracker" },

  // Usage/crash/marketing analytics (telemetry, not ad-serving)
  { domain: "google-analytics.com", category: "analytics" },
  { domain: "googletagmanager.com", category: "analytics" },
  { domain: "app-measurement.com", category: "analytics" },
  { domain: "crashlytics.com", category: "analytics" },
  { domain: "mixpanel.com", category: "analytics" },
  { domain: "amplitude.com", category: "analytics" },
  { domain: "segment.io", category: "analytics" },
  { domain: "segment.com", category: "analytics" },
  { domain: "hotjar.com", category: "analytics" },
  { domain: "fullstory.com", category: "analytics" },
  { domain: "mouseflow.com", category: "analytics" },
  { domain: "scorecardresearch.com", category: "analytics" },
  { domain: "quantserve.com", category: "analytics" },
  { domain: "flurry.com", category: "analytics" },
  { domain: "newrelic.com", category: "analytics" },
  { domain: "nr-data.net", category: "analytics" },
  { domain: "sentry.io", category: "analytics" },
  { domain: "bugsnag.com", category: "analytics" },
  { domain: "branch.io", category: "analytics" },
  { domain: "appsflyer.com", category: "analytics" },
  { domain: "urbanairship.com", category: "analytics" },
  { domain: "braze.com", category: "analytics" },
  { domain: "2o7.net", category: "analytics" },
  { domain: "omtrdc.net", category: "analytics" },
];
